[package]
name = "transpile_zork"
version = "0.1.0"
authors = ["Liam"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.2"
regex = "1.8.3"
